apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: KUBE_CLUSTER_CERTIFICATE
    server: https://api.KUBE_CLUSTER_NAME
  name: KUBE_CLUSTER_NAME
contexts:
- context:
    cluster: KUBE_CLUSTER_NAME
    user: KUBE_CLUSTER_NAME
  name: KUBE_CLUSTER_NAME
current-context: KUBE_CLUSTER_NAME
kind: Config
preferences: {}
users:
- name: KUBE_CLUSTER_NAME
  user:
    client-certificate-data: KUBE_CLIENT_CERTIFICATE
    client-key-data: KUBE_CLIENT_KEY
    password: KUBE_ADMIN_PWD
    username: admin
- name: KUBE_CLUSTER_NAME-basic-auth
  user:
    password: KUBE_ADMIN_PWD
    username: admin